# Dataset -------------------------------
dataset_params:
  test_size: 0.1
  window: 200
  stride: 10
  telescope: 10
# Model ------------------------------
name: Model00
compile_params:
  optimizer: !optimizer
    type: Adam
    params:
      learning_rate: !float 1e-4
  loss: !loss
    type: CategoricalCrossentropy
    params:
  metrics:
    - accuracy
fit_params:
  epochs: 200
  callbacks:
# Architecture -----------------------
input_layer: !layer
  type: Input
  params:
    shape: !tuple [256, 256, 3 ]
    name: Input
output_layer: !layer
  type: Dense
  params:
    units: 14
    activation: softmax
    name: Output
hidden_layers:
  - !network
    type: VGG16
    params:
      locked_layers: 14
      initialize: imagenet
  - !sequential
    - !layer
      type: Dense
      params:
        units: 16
        kernel_initializer: !initializer
          type: 'GlorotUniform'
          params:
            seed: 42
